apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  namespace: hello-world
spec:
  rules:
  - host: hello-world-dv1.sti.codes
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: 80
